language: generic 
os:
  - "linux"

services:
  - docker

before_install:
  - docker build -t rainerza/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rainerza/client-test npm run test

after_success:
  - export BRANCH=$(git rev-parse --abbrev-ref HEAD)
  - echo "TRAVIS_TEST_RESULT: $TRAVIS_TEST_RESULT"
  - echo "BRANCH: $BRANCH"
  - if [ $TRAVIS_TEST_RESULT == 0 ] && [ "$BRANCH" == "master" ]; then docker build -t rainerza/multi-client ./client; fi
  - if [ $TRAVIS_TEST_RESULT == 0 ] && [ "$BRANCH" == "master" ]; then docker build -t rainerza/multi-nginx ./nginx; fi
  - if [ $TRAVIS_TEST_RESULT == 0 ] && [ "$BRANCH" == "master" ]; then docker build -t rainerza/multi-server ./server; fi
  - if [ $TRAVIS_TEST_RESULT == 0 ] && [ "$BRANCH" == "master" ]; then docker build -t rainerza/multi-worker ./worker; fi
  # Log in to the docker CLI
  - if [ $TRAVIS_TEST_RESULT == 0 ] && [ "$BRANCH" == "master" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin; fi
  # Take those images and push them to dockerhub
  - if [ $TRAVIS_TEST_RESULT == 0 ] && [ "$BRANCH" == "master" ]; then docker push rainerza/multi-client; fi
  - if [ $TRAVIS_TEST_RESULT == 0 ] && [ "$BRANCH" == "master" ]; then docker push rainerza/multi-nginx; fi
  - if [ $TRAVIS_TEST_RESULT == 0 ] && [ "$BRANCH" == "master" ]; then docker push rainerza/multi-server; fi
  - if [ $TRAVIS_TEST_RESULT == 0 ] && [ "$BRANCH" == "master" ]; then docker push rainerza/multi-worker; fi

# deploy:
#   # edge: true
#   provider: elasticbeanstalk
#   region: "eu-west-2"
#   app: "multi-docker"
#   env: "MultiDocker-env"
#   bucket: "elasticbeanstalk-eu-west-2-925871616603"
#   bucket_path: "multi-docker"
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
#   on:
#     branch: master